# Generated by Django 5.2.12 on 2026-05-19 07:00

import django.db.models.deletion
import pretix.base.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pretixbase", "0299_itemprogramtime_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("settled", models.DateTimeField(null=True)),
                ("order_code", models.CharField(max_length=16)),
                ("email", models.EmailField(db_index=True, max_length=190)),
                ("name", models.CharField(max_length=255)),
                ("message", models.TextField(null=True)),
                ("locale", models.CharField(max_length=32)),
                ("internal_notes", models.TextField(null=True)),
                (
                    "event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="withdrawals",
                        to="pretixbase.event",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to="pretixbase.order",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to="pretixbase.organizer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, pretix.base.models.base.LoggingMixin),
        ),
    ]
