# Generated by Django 5.2.12 on 2026-06-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretix_withdrawal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawal",
            name="order_code",
            field=models.CharField(max_length=67),
        ),
    ]
